name: space_element
description: SpaceElement Ignite your cosmic curiosity with this captivating app that brings the wonders of outer space to your fingertips. Explore, learn, and play with stunning visuals, interactive tours, and engaging quizzes. Embark on a journey through the universe without leaving your device.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.6
  animated_rotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1


flutter:


  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/icons/


  fonts:
     - family: Gilroy
       fonts:
         - asset: lib/assets/fonts/gilroy_semibold.ttf
#         - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: Mark
       fonts:
         - asset: lib/assets/fonts/markpro_regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
